
# 비번이 자꾸 안됨 ㅅ빌
services:
  db-mysql:
    container_name: db-mysql
    image: mysql:8.0.32
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: demo
    ports:
      - 3307:3309
    networks:
      - springboot-mysql-net

  test-app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - db-mysql
    networks:
      - springboot-mysql-net
    restart: on-failure


networks:
  springboot-mysql-net:
    driver: bridge
